version: "3.1"

services:
  pilot-4-podman:
    build:
      context: .
      args:
        LOCAL_DIR: ./submissions-pilot2
        IMAGE_ORG: rocker
        IMAGE_REGISTRY: docker.io
        R_VERSION: 4.2.0
    ports:
      - "8787:8787"
