version: "3.1"

services:
  pilot-4-podman-rhino:
    build:
      context: ..
      args:
        IMAGE_ORG: rocker
        IMAGE_REGISTRY: docker.io
        R_VERSION: 4.3.0
        LOCAL_DIR: ./rhino/pilot2-modified
        R_SCRIPT: ./rhino/entrypoint.R
    ports:
      - "9797:8787"
