version: "3.1"

services:
  pilot-4-podman-rhino:
    build:
      context: .
      dockerfile: ../Dockerfile
      args:
        IMAGE_ORG: rocker
        IMAGE_REGISTRY: docker.io
        R_VERSION: 4.3.0
        LOCAL_DIR: ./pilot2-modified
        R_SCRIPT: ./entrypoint.R
    ports:
      - "9797:8787"
