name: Demo Push

on:
  push:
  pull_request:

env:
  IMAGE_NAME: pilot4-renv-cache
  R_VERSION: 4.2.0
  RENV_PATHS_LOCKFILE: renv_cache/renv.lock
  RENV_PATHS_ROOT: renv_cache/.cache
  RENV_PATHS_CELLAR: submissions-pilot2/renv/cellar

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  container-build:
    runs-on: ubuntu-latest

    steps:
      - name: System deppendencies
        run: |
          sudo apt update -q
          sudo apt install -y -q qemu-user-static

      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ env.R_VERSION }}
          # Use "renv" to retrieve R version recorded in renv.lock file.

      - uses: r-lib/actions/setup-renv@v2

      - name: list cache 1
        run: |
          ls -lna

      - name: list cache 2
        run: |
          ls -lna renv_cache/

      - name: list cache 3
        run: |
          ls -lna renv_cache/.cache

      - name: Buildah Action
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          context: ./renv_cache
          tags: v1
          containerfiles: |
            ./renv_cache/Dockerfile
          build-args: |
            R_VERSION=${{ env.R_VERSION }}
